# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Sexual disparities in Police Stops across the US
tagline:          'Team BEB'
description:      'Sexual disparities in Police Stops across the US'
url:              https://ada-beb.github.io/
baseurl:          /

author:
  name:           'Aaron Lippeveldts, Alpha Diallo, Melike Geçer'
  url:            https://ada-beb.github.io/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ADA-BEB/ADA-BEB.github.io
